services:
  mysql-db:
    image: mysql:9
    container_name: my_car_workshop_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segreta
      MYSQL_DATABASE: my_car_workshop_db
      MYSQL_USER: workshop_user
      MYSQL_PASSWORD: workshop_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: