spring.application.name=backend

# ==========================================
# Configurazione Connessione MySQL
# Indica a Spring la posizione del database e le credenziali di accesso 
# (che combaciano con quelle definite nel file Docker)
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/my_car_workshop_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=workshop_user
spring.datasource.password=workshop_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configurazione JPA e Hibernate

# spring.jpa.hibernate.ddl-auto=update 
# dice all'ORM (object relational mapping) Hibernate di analizzare le classi Java (Entità JPA)
# e di creare o modificare automaticamente lo schema e le tabelle nel DB MySQL senza dover scrivere codice SQL a mano

# spring.jpa.show-sql=true
# stampa le query SQL direttamente nella console di Spring

# spring.jpa.open-in-view=false
# forza l'applicazione a chiudere la connessione col DB 
# non appena la transazione è terminata, rendendo il sistema più sicuro e performante

# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false